/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Hq6dPr1vDbo
 */
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { CardHeader, CardContent, Card } from "@/components/ui/card"
import { CarouselItem, CarouselContent, CarouselPrevious, CarouselNext, Carousel } from "@/components/ui/carousel"

export function postComponent() {
  return (
    (<div className="flex flex-col w-full max-w-2xl mx-auto">
      <Carousel className="w-full max-w-xs">
        <CarouselContent>
          <CarouselItem>
            <div className="p-1">
              <Card>
                <CardHeader className="flex items-center gap-2">
                  <Avatar className="w-8 h-8 border">
                    <AvatarImage alt="@user1" src="/placeholder-user.jpg" />
                    <AvatarFallback>U1</AvatarFallback>
                  </Avatar>
                  <span className="text-sm font-semibold">@user1</span>
                </CardHeader>
                <CardContent className="flex aspect-square items-center justify-center p-6">
                  <img
                    alt="Story 1"
                    className="aspect-square object-cover"
                    height={400}
                    src="/placeholder.svg"
                    width={400} />
                </CardContent>
              </Card>
            </div>
          </CarouselItem>
          <CarouselItem>
            <div className="p-1">
              <Card>
                <CardHeader className="flex items-center gap-2">
                  <Avatar className="w-8 h-8 border">
                    <AvatarImage alt="@user2" src="/placeholder-user.jpg" />
                    <AvatarFallback>U2</AvatarFallback>
                  </Avatar>
                  <span className="text-sm font-semibold">@user2</span>
                </CardHeader>
                <CardContent className="flex aspect-square items-center justify-center p-6">
                  <img
                    alt="Story 2"
                    className="aspect-square object-cover"
                    height={400}
                    src="/placeholder.svg"
                    width={400} />
                </CardContent>
              </Card>
            </div>
          </CarouselItem>
          <CarouselItem>
            <div className="p-1">
              <Card>
                <CardHeader className="flex items-center gap-2">
                  <Avatar className="w-8 h-8 border">
                    <AvatarImage alt="@user3" src="/placeholder-user.jpg" />
                    <AvatarFallback>U3</AvatarFallback>
                  </Avatar>
                  <span className="text-sm font-semibold">@user3</span>
                </CardHeader>
                <CardContent className="flex aspect-square items-center justify-center p-6">
                  <img
                    alt="Story 3"
                    className="aspect-square object-cover"
                    height={400}
                    src="/placeholder.svg"
                    width={400} />
                </CardContent>
              </Card>
            </div>
          </CarouselItem>
        </CarouselContent>
        <CarouselPrevious />
        <CarouselNext />
      </Carousel>
      <div className="w-full h-1 mt-2 bg-gray-200 rounded">
        <div
          className="h-full bg-blue-500 rounded"
          style={{
            width: "33%",
          }} />
      </div>
    </div>)
  );
}
